---
- hosts: asa
  gather_facts: False

  vars_prompt:
    - name: 'ansible_ssh_pass'
      prompt: 'SSH Password'
      private: True

  tasks:
  - name: Enumerate interface names
    asa_command:
      commands: show run | in ^ *nameif
      provider: '{{ cli }}'
    register: results

  - name: Parse interface names and assign to a variable
    set_fact:
      int_names: '{{ results.stdout_lines[0] | map("regex_replace", "nameif\s", "") | list }}'

  - debug:
      var: int_names
...