---
- hosts: panos
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Get HA State
      panos_op:
        provider: "{{ provider }}"
        cmd: show high-availability state
      register: ha_info

    - name: Parse HA State
      xml:
        xmlstring: "{{ ha_info.stdout_xml }}"
        xpath: //enabled
        content: text
      register: ha_state

    - name: Save HA State
      set_fact:
        ha_enabled: "{{ ha_state.matches[0].enabled }}"

    - block:
        - name: Parse HA Role
          xml:
            xmlstring: "{{ ha_info.stdout_xml }}"
            xpath: //group/local-info/state
            content: text
          register: ha_role

        - name: Save HA State
          set_fact:
            ha_role: "{{ ha_role.matches[0].state }}"
      when: ha_enabled

    - block:
        - debug:
            msg: "{{ ha_enabled }} {{ ha_role }}"

        - name: Get Preemptive State
          panos_type_cmd:
            provider: "{{ provider }}"
            cmd: show
            xpath: "devices/entry[@name='localhost.localdomain']/deviceconfig/high-availability/group//election-option/preemptive"
          register: preemptive_state

        - name: Parse Preemptive State
          xml:
            xmlstring: "{{ preemptive_state.stdout_xml }}"
            xpath: /preemptive
            content: text
          register: preemptive_state

        - name: Save Preemptive State
          set_fact:
            preemptive_enabled: "{{ preemptive_state.matches[0].preemptive }}"

        - name: Disable Preemptive
          panos_type_cmd:
            provider: "{{ provider }}"
            cmd: set
            xpath: /config/devices/entry[@name='localhost.localdomain']/deviceconfig/high-availability/group/entry/election-option
            element: <preemptive>no</preemptive>
          when: preemptive_enabled
          register: preemptive_state

        - debug:
            var: preemptive_state.changed

        - name: Commit configuration
          panos_commit:
            provider: "{{ provider }}"
          when: preemptive_state.changed
      when: ha_enabled and ha_role == "active"
