---
- hosts: panos
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Get PAN-OS Facts
      panos_facts:
        provider: "{{ provider }}"
        gather_subset: ["system", "ha"]

    - name: Get HA Preemptive State
      block:
        - name: Set HA Preemptive State To False
          set_fact:
            preemptive_enabled: False

        - name: Get HA Preemptive State
          panos_type_cmd:
            provider: "{{ provider }}"
            cmd: show
            xpath: /config/devices/entry[@name='localhost.localdomain']/deviceconfig/high-availability/group//election-option/preemptive
          register: results
          failed_when: False

        - name: Parse HA Preemptive State
          block:
            - name: Parse HA Preemptive State
              xml:
                xmlstring: "{{ results.stdout_xml }}"
                xpath: /preemptive
                content: text
              register: preemptive_state

            - name: Save HA Preemptive State
              set_fact:
                preemptive_enabled: "{{ preemptive_state.matches[0].preemptive }}"
          when: results.stdout_xml is defined

        - name: Output Results
          debug:
            var: preemptive_enabled
          when: preemptive_enabled
      when: ansible_net_ha_enabled
