---
- hosts: panos
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Get PAN-OS Facts
      panos_facts:
        provider: "{{ provider }}"
        gather_subset: ["system", "ha"]

    - name: Disable HA Preemptive
      block:
        - name: Set HA Preemptive State To False
          set_fact:
            preemptive_enabled: False

        - name: Get HA Preemptive State
          panos_type_cmd:
            provider: "{{ provider }}"
            cmd: show
            xpath: /config/devices/entry[@name='localhost.localdomain']/deviceconfig/high-availability/group//election-option/preemptive
          register: results
          failed_when: False

        - name: Parse HA Preemptive State
          block:
            - name: Parse HA Preemptive State
              xml:
                xmlstring: "{{ results.stdout_xml }}"
                xpath: /preemptive
                content: text
              register: preemptive_state

            - name: Save HA Preemptive State
              set_fact:
                preemptive_enabled: "{{ preemptive_state.matches[0].preemptive }}"
          when: results.stdout_xml is defined

        - name: Disable HA Preemptive
          panos_type_cmd:
            provider: "{{ provider }}"
            cmd: set
            xpath: /config/devices/entry[@name='localhost.localdomain']/deviceconfig/high-availability/group/entry/election-option
            element: <preemptive>no</preemptive>
          register: preemptive_state_8_0
          when: ansible_net_version is match('8.0') and preemptive_enabled

        - name: Disable HA Preemptive
          panos_type_cmd:
            provider: "{{ provider }}"
            cmd: set
            xpath: /config/devices/entry[@name='localhost.localdomain']/deviceconfig/high-availability/group/election-option
            element: <preemptive>no</preemptive>
          register: preemptive_state_8_1
          when: ansible_net_version is match('8.1') and preemptive_enabled

        - name: Commit Configuration
          panos_commit:
            provider: "{{ provider }}"
            admins: ["migration"]
          when: preemptive_state_8_0.changed or preemptive_state_8_1.changed
      when: ansible_net_ha_enabled
