---
- hosts: staging
  gather_facts: False

  tasks:
  - name: Generate Intial Configuration Files
    template:
      src: templates/initial_config.j2
      dest: templates/output/initial_configuration/initial_configuration-{{ inventory_hostname }}.txt
    delegate_to: localhost
...