---
- hosts: panos
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Show Config Set
      panos_op:
        provider: "{{ provider }}"
        cmd: "{{ item }}"
      register: config_set
      with_items:
        - set cli config-output-format set
        - configure
        - show

    - name: Output Config Set
      debug:
        var: config_set.results[2].stdout_lines[0]
