---
- hosts: panos
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Show System Resource
      panos_op:
        provider: "{{ provider }}"
        cmd: show running resource-monitor
      register: sys_resources_mon

    - name: Output System Resource Monitor
      debug:
        var: sys_resources_mon.stdout_lines[0]
