---
- hosts: panos
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Show System Info
      panos_op:
        provider: "{{ provider }}"
        cmd: show system info
      register: sys_info

    - name: Output System Info
      debug:
        var: sys_info.stdout_lines[0]
